### ISSUE TITLE
Trouble moving from Grunt to Nunjucks CLI

### ISSUE THREAD

**Issue by DePasqualeOrg** [jeremyben/nunjucks-cli#14]
I've previously been using Grunt to compile my templates as part of my build process, but now I'd like to move to npm scripts. The documentation for the Nunjucks CLI is limited, and I'm having trouble figuring out how to express my grunt task in the CLI. Here is my Grunt task:

```
nunjucks: {
	options: {
		data: grunt.file.readJSON('template-data.json'),
		paths: ['', '../templates/']
	},
	html: {
		files: [{
			expand: true,
			cwd: 'dev/',
			src: ['*.html.njk'],
			dest: 'dev/',
			ext: '.html'
		}]
	},
	scss: {
		files: [{
			expand: true,
			cwd: 'dev/css/',
			src: ['*.scss.njk'],
			dest: 'dev/css/',
			ext: '.scss'
		}]
	}
},
```

How can I do the same thing with the Nunjucks CLI?

**Comment by jeremyben** [comment]
You should directly use the nunjucks module if you want custom configuration. This is a pretty basic CLI tool.
