### ISSUE TITLE
.html extension can't be used for input even in safe cases

### ISSUE THREAD

**Issue by thijsvandien** [jeremyben/nunjucks-cli#6]
nunjucks-cli refuses to render any files that have the `.html` extension to "avoid overwriting your templates". That can only happen if the the rendered files were to be written to the same folder as where the input resides. Often that is not the case, e.g. when specifying the output folder explicitly to be a different one.

**Comment by homosaur** [comment]
This feature seems like it could be desirable under a flag, but what is your use case for it, @thijsvandien? It would seem to me like the reason to care about the extension is that your text editor is not highlighting the code correctly and that is easily configurable in your editor. Can you elaborate a bit on why you want this?

**Comment by darklynx** [comment]
I'm also voting for support of this feature: allow templates to have *.html extension.
Templates are HTML files with some extended syntax so, why not to let any editor immediately recognize it as HTML via extension?

My use case it npm script:

```
"scripts": {
  "build-html": "nunjucks *.html -p src/html/ -o dist/",
  ...
}
```

There is no way that problem described in warning message can happen:

> To avoid overwriting your templates, do not use html as file extension

**Comment by darklynx** [comment]
Also the example in [Nunjucks official documentation](https://mozilla.github.io/nunjucks/templating.html) uses html extension for templates:

```
{% extends "parent.html" %}

{% block left %}
This is the left side!
{% endblock %}

{% block right %}
This is the right side!
{% endblock %}
```

**Comment by thijsvandien** [comment]
Indeed, I am not a fan of custom extensions where there are acceptable standard ones. As @darklynx said, .html is semi-offical here. Source files being overwritten is an exceptional case, the guard for which has a disproportional impact on the happy path.

**Comment by darklynx** [comment]
I find the idea of @homosaur is really good: add a special cli flag to allow .html extension for templates. By default for inexperienced users the tool will refuse to accept templates under .html extension, however the more experienced users may enable this possibility and they were already warned by default behavior and warning message.

**Comment by thijsvandien** [comment]
Initially I was thinking of simply comparing the input folder to the output folder and not warning if they're distinct, since nothing can happen then. Having given it some more thought, I realize it may not be that easy when relative paths get involved. There is no such thing as _the_ input folder and _the_ output folder. Instead, the program would have to make a list of files that are going to be read and files that are going to be written, before actually doing so, and from that determine if there are going to be conflicts. As much as I'd like to keep the API minimal, the implementation simplicity of a flag has a strong edge here, unless there are other advantages to such preprocessing (caching?).

**Comment by jeremyben** [comment]
Sorry for the delay.
You guys are right, I will implement in the next days a simple boolean flag to allow use of .html.

For the record, I chose to forbid the use of .html as a source, simply because I overwrote a lot of my source files during the developement of this module, and it made me precautious about it.
